- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: replace in CC_LOOKUPS
      shell: sed "/CC_LOOKUPS/s/0/1/" /etc/csf/csf.conf -i
    - name: replace in CC_IGNORE
      shell: sed '/CC_IGNORE/s/CC_IGNORE.*/CC_IGNORE = "CL"/' /etc/csf/csf.conf -i
    - name: replace in MM_LICENSE_KEY
      shell: sed '/MM_LICENSE_KEY/s/MM_LICENSE_KEY.*/MM_LICENSE_KEY = "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"/' /etc/csf/csf.conf -i
    - name: Reiniciando el CSF
      ansible.builtin.shell:
          cmd: csf -ra
 - name: Permitir diariamente actualizar la configuracion de el csf 
      ansible.builtin.cron:
          name: "actualizar CSF cada 4 horas"
          minute: "0"
          hour: "*/6"
          job: "wget -q -O /root/csf_reconfigure.yml https://raw.githubusercontent.com/itfinden/CSF_playbook_itfinden/main/csf_reconfigure.yml && ansible-playbook /root/csf_reconfigure.yml >/dev/null 2>&1"
