- hosts: all
  become: yes
  tasks:
    - name: agregando nameserver resolv
      blockinfile:
        path: /etc/resolv.conf
        block: |
            'nameserver 9.9.9.9'
            'nameserver 1.1.1.1'
