- hosts: 127.0.0.1
  connection: local  
  tasks:
    - name: Copiamos la configuracion base del agente zabbix 
      ansible.builtin.copy:
          dest: /etc/snmp/snmpd.conf
          #si el archivo existe lo sobre escribe
          backup: true
          content: |
            rocommunity itfinden 209.145.63.249
            rocommunity itfinden 45.226.170.110
            rocommunity itfinden 38.7.206.126
            syslocation  Santiago,Chile
            syscontact  soporte@itfinden.com
          
              
              
              

